#!/bin/bash

# Test for OSPL_HOME env var, required for the script
if [ -z "$OSPL_HOME" ]
then
  echo OpenSplice environment does not appear to be set up -- exiting
  exit
fi

# Add the required jars to classpath
CP=$OSPL_HOME/jar/dcpssaj.jar:./lib/spectrum.jar:./lib/outline.jar:./lib/oric_rdsm.jar:./lib/gson-1.7.jar

# Add DDS idl generated data classes/jars here
CP=$CP:./lib/DDSSolarSystem.jar:./lib/DDSFastImageStream.jar:./lib/DDSDeltaImageStream.jar

java -cp $CP orbisoftware.hlatools.spectrumhlamonitor.SpectrumHLAMonitor
